# Generated by Django 4.2.4 on 2023-08-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentcsv_csv_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcsv',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcsv',
            name='csv_file',
            field=models.FileField(upload_to='student_csv/'),
        ),
    ]
