# Generated by Django 4.2.4 on 2023-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_studentcsv_file_name_alter_studentcsv_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_created=True)),
                ('otp', models.CharField(max_length=10)),
                ('otp_usn', models.CharField(max_length=100)),
            ],
        ),
    ]
