# Generated by Django 4.2.4 on 2023-09-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='time_stamp',
        ),
    ]
