# Generated by Django 4.2.5 on 2023-09-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_otp_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('dept', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=4)),
                ('capacity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(blank=True, max_length=32)),
                ('sub_name', models.CharField(blank=True, max_length=199)),
                ('dept', models.CharField(blank=True, max_length=299)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.add_staff')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.studentdata')),
            ],
        ),
    ]
