# Generated by Django 4.2.5 on 2023-09-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_staff_room_subjects_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Student_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('subname', models.CharField(blank=True, max_length=100)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept')),
            ],
        ),
        migrations.AlterField(
            model_name='add_staff',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept'),
        ),
    ]
