# Generated by Django 4.2.5 on 2023-09-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_subjects_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_student_link',
            name='stu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.studentdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject_student_link',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.elective'),
        ),
    ]
