# Generated by Django 4.2.5 on 2023-09-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_student_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='elective',
            name='subname',
            field=models.CharField(max_length=100),
        ),
    ]
