# Generated by Django 4.2.5 on 2023-09-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_elective_code_alter_elective_subname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elective',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='elective',
            name='subname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='photo',
            field=models.ImageField(upload_to='p_photo/'),
        ),
    ]
