# Generated by Django 4.2.5 on 2023-09-23 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_elective_code_alter_elective_subname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('detp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subjects')),
            ],
        ),
    ]
