# Generated by Django 4.2.5 on 2023-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_time_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='elective',
            name='seme',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentdata',
            name='sem',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
